import {
  Cheese,
  Pepper,
  Noodles,
  Eggs,
  ParsleyFlakes,
  Basil,
  Salt,
  TomatoSauce,
  CanOfTomatoes,
  Garlic,
  DicedOnions,
  GroundBeef,
} from "ingredients"

export const Lasagna = {
  title: "Lasagna",
  ingredients: [
    GroundBeef(),
    DicedOnions("1/2 cup"),
    Garlic("1 tsp", "minced"),
    CanOfTomatoes("14.5 Oz | 16 oz", "diced"),
    CanOfTomatoes("12 oz", "paste"),
    TomatoSauce("15 oz"),
    Basil("2 tsp", "dried & crushed"),
    Salt("1 tsp"),
    Noodles("8 oz", "Lasagna"),
    Eggs(2),
    Cheese("2 1/2 cups", "Riccotta"),
    Cheese("3/4 cup", "Parmesan"),
    ParsleyFlakes("2 tbs"),
    Cheese("1 lb", "Grated Mozerrela"),
    Pepper(),
  ],
  directions: [
    { type: "section", text: "Prep" },
    { type: "step", text: "casserole dish" },
    { type: "step", text: "oven to 375 degrees" },
    { type: "step", text: "big mixing bowl for cheese mix" },
    { type: "step", text: "2 big stove pans, 1 for bowling noodles and 1 for meat" },
    { type: "section", text: "Meat" },
    { type: "step", text: "cook low heat onion and garlic til lightly brown in a pan" },
    { type: "step", text: "add in ground beef and mix til meat is cooked" },
    { type: "step", text: "add all tomatoes (diced, sauce, and paste) with salt, and basil." },
    { type: "step", text: "let simmer for 15 minutes" },
    { type: "section", text: "Noodles" },
    { type: "step", text: "grab a big pan and boil noodles" },
    { type: "step", text: "at about 12-15 minutes check and strain" },
    { type: "section", text: "Make cheese paste" },
    { type: "step", text: "beat the eggs and ricotta" },
    { type: "step", text: "add 1/2 cup of parmesan, parsley, salt, pepper" },
    { type: "section", text: "Layer it up" },
    { type: "step", text: "in a casserole dish, make your layers." },
    { type: "step", text: "start with a little meat sauce to grease the bottom of the pan" },
    { type: "step", text: "next lay 4~ noodles, cover the whole dish" },
    { type: "step", text: "follow with half of the ricotta cheese on top" },
    { type: "step", text: "half of the mozerella cheese on top of that" },
    { type: "step", text: "following the cheese comes half of the meat sauce. " },
    { type: "step", text: "repeat starting from noodles" },
    { type: "section", text: "Bake" },
    { type: "step", text: "toss it in the oven for 30-35 minutes" },
  ],
}
